apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  workflow_dispatch:
    inputs:
      s1:
        type: string
        default: hell world
        description: a string
      c1:
        type: choice
        options:
          - option1
          - option2
          - option3
        default: ""
        description: a choice
      n1:
        type: number
        default: 1
        description: a number
        required: true
      b1:
        type: boolean
        default: true
        description: a boolean
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
